[package]
name = "eca"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.25"
futures-util = "0.3.25"
rust-crypto = "0.2.36"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["full"] }
warp = "0.3.3"
